---
- name: Configure VM with required packages and user
  hosts: azure_vms
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - htop
          - curl
        state: present

    - name: Create new user
      user:
        name: eseroghene   
        shell: /bin/bash
        create_home: yes
        state: present
